### ISSUE TITLE
typing comment

### ISSUE THREAD

**Issue by Candidesk8** [gsantner/dandelion#142] opened 2017-02-13 07:11 UTC
#### General information
* ** FairPhone FP1U :**
* ** Android 4.2.2 :**
* ** pod.framasphere.org :**
* ** 0.6.0.0-pba27cf8f :**
* ** F-Droid :**
* ** 0.2.2 (12) :**

#### Steps to reproduce

This is a new bug report. I am still using the application :-)

1. writing a comment on a post
2. want to submit it, touching the button
3. the keyboard disappear but the background don't follow, had to touch again the button to submit the post

#### Expected result
**What is the expected output?** 
keyboard retract and app send post
**What do you see instead?**
a blank and touch didn't do what's expected.

Screenshot :
commenting the post
![](https://framapic.org/VVDVpNO1NNi0/Q9T0dnr9ViSP)

the blank appearing
![](https://framapic.org/x0sUTvp6o5GW/yrDJWT0VBCUI)

final normal position after scrolling the screen
![](https://framapic.org/xkacJcfGQnfE/4GeZDcNgTP2x)

**Comment by vanitasvitae** [comment] 2017-02-13 09:22
Hi!
Thank you for your feedback. Unfortunately I cannot reproduce this on my device. This is likely to be an upstream bug of the WebView.
Just to make sure: Posting comments works in general and this is only a visual inconvenience, right?

**Comment by Candidesk8** [comment] 2017-02-13 11:20
visual and practical, also ...
But comments works.

**Comment by gsantner** [comment] 2017-02-13 12:07
Can you try another pod - if this happens there also?

**Comment by Candidesk8** [comment] 2017-02-13 12:11
Unfortunately, I don't own another account on a different pod.
but if you have a test one I could use, please let me know.

**Comment by gsantner** [comment] 2017-02-13 22:34
Tried it on my 4.2.2 device, couldn't find any issue there. I can suggest you to register on another pod (sorry, we won't post any credentials; you can register with any email at any pod) and try if it also happens there. But I'm pretty sure the webview implementation of your device is somehow bugged, and we can't do much about that, but suggest to update to a newer android version which maybe has fixes. I read that at least Android 4.4 is available for your device.

**Comment by Candidesk8** [comment] 2017-02-17 07:09
Hi!
I opened another account on freehuman.fr and the bug happens too.
I red that too, but it's on an unofficial rom, I guess...

**Comment by vanitasvitae** [comment] 2017-02-17 18:31
I'll close this for now, since there's not much we can do about it and its probably an upstream issue. Thank you for reporting anyway :)

**Closed as completed by vanitasvitae** 2017-02-17 18:31 UTC
Labels: bug
