### ISSUE TITLE
1/3 of top toolbar covered up after switching orientation.

### ISSUE THREAD

**Issue by teslasmoustache** [gsantner/dandelion#87] opened 2016-10-19 14:41 UTC
#### General information
- **Device:** HTC One M7
- **Android Version:** Cyanogenmod 12.1
- **Pod:** diasp.org
- **Diaspora pod version:** 0.6.0.1-p3a614d9e
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** 0.1.6

#### Steps to reproduce
1. …Open app, turn on "Intellihide Toolbars"
2. …Load Stream, scroll down, turn orientation from vertical to horizontal.
3. ...Turn screen back to vertical orientation.
#### Expected result

**What is the expected output?** Everything should look normal

**What do you see instead?** The top ~1/3 of the top toolbar is covered up by my notification tray. (The top bar in Android. Forget what it's called.)

Upload screenshots via drag&drop if needed and apply resizing:
`<img width="30%" height="30%" src="https://diasp.org/uploads/images/scaled_full_cc83a6943ecf6fdea136.png">`

**Comment by vanitasvitae** [comment] 2016-10-19 14:53
Thank you for opening this issue report. I tried to reproduce the issue on my phone (Nexus 6p, Android N), but without success. 

Does the issue have any more negative side effects (Is the top bar stuck after changing orientation?), or is it just a visual issue?

Also does this happen all the time when you switch orientation?

**Comment by teslasmoustache** [comment] 2016-10-19 15:30
Only a visual issue. And yes, happens every time I switch orientation. In fact,  I have just noticed it happens directly when I switch from vertical to horizontal.

Is the a lock orientation setting?...

**Comment by vanitasvitae** [comment] 2016-10-19 15:55
No, but you could lock orientation in android to circumvent this.

**Comment by teslasmoustache** [comment] 2016-10-19 16:00
Fair enough. There are apps which I like to change orientation for sometimes. Diaspora's just not one of them. So I think it would be cool to consider a lock orientation option in a future release.

**Comment by vanitasvitae** [comment] 2016-10-20 16:58
We'll put it on the todo list :)

**Comment by vanitasvitae** [comment] 2016-10-24 22:53
See #92 
I'll close this now, since I can't reproduce the issue. If anyone has an Idea, let us know :)

**Closed as completed by vanitasvitae** 2016-10-24 22:53 UTC
Labels: bug
