### ISSUE TITLE
draft messages are lost if orientation changes

### ISSUE THREAD

**Issue by pravi** [gsantner/dandelion#64] opened 2016-09-03 04:09 UTC
When posting a new mesage in portrait, if orientation changes, message being typed is lost and stream is shown. Its very irritating to type again.

Even regular stream gets reloaded when orientation changes.
#### General information
- **Device:** Yu Yuphoroa
- **Android Version:** Cyanogen Mod 12.1
- **Pod:** poddery.com
- **Diaspora pod version:** 0.6.0.0
- **App source:** F-Droid
- **App version:** 0.1.5
#### Steps to reproduce
1. …create a new post
2. …type something
3. …change orientation
#### Expected result

What is the expected output? 

You should not lose the message you typed.

Stream is loaded instead.

**Comment by vanitasvitae** [comment] 2016-09-03 05:53
Can't reproduce that one. Make sure you do NOT have something like "Don't keep activities" checked in the developer options.

**Comment by pravi** [comment] 2016-09-03 08:12
@vanitasvitae I don't have that option checked, though I could not reproduce it on HTC Desire 816G with Android 4.4.2. What version of Android do you have?

**Comment by vanitasvitae** [comment] 2016-09-03 08:14
@pravi: I'm running a Nexus 5 with CopperheadOS (Android 6). Thr issue could be caused by limited RAM I guess?

Am 3. September 2016 10:12:02 MESZ, schrieb Praveen Arimbrathodiyil notifications@github.com:

> @vanitasvitae I don't have that option checked, though I could not
> reproduce it on HTC Desire 816G with Android 4.4.2. What version of
> Android do you have?
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaspora-for-Android/diaspora-android/issues/64#issuecomment-244533810

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by pravi** [comment] 2016-09-03 08:46
@vanitasvitae browser does orientation switching without any issues, so I doubt it is RAM. It has 2GB RAM.

**Comment by gsantner** [comment] 2016-09-03 10:15
Good if it does, but it shouln't save the content. Usually an orientation change let your android re-render the layout. (onCreate called ;).  Btw: Text also stays on my device.

`Bundle savedInstanceState` may be a good hint, if someone goes onto this.

**Comment by vanitasvitae** [comment] 2016-09-03 12:51
But isn't the content saved in onPause or onSaveWebViewState or something like that?

Am 3. September 2016 12:15:42 MESZ, schrieb Gregor Santner notifications@github.com:

> Good if it does, but it shouln't save the content. Usually an
> orientation chagne lets your android re-render the layout. (onCreate
> called ;). 
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaspora-for-Android/diaspora-android/issues/64#issuecomment-244538546

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by vanitasvitae** [comment] 2016-09-05 19:03
@pravi Could you try this _experimental_ [apk?](https://vanitasvitae.no-ip.biz/nextcloud/index.php/s/oEu3tGymA5DynEQ) I made some experimental changes and the apk is signed with my key, so you have to reinstall the app. Also the download might be a little slow. I hope this might change your problem and also make the app a little faster ;)

**Comment by vanitasvitae** [comment] 2016-09-08 08:20
I merged the changes that I made in the experimental branch into the master branch. Please reopen, if the problem still occurs.

**Comment by gsantner** [comment] 2016-09-11 21:39
Bookmark: http://code.hootsuite.com/orientation-changes-on-android/

**Comment by vanitasvitae** [comment] 2016-09-20 17:54
This is now fixed.

**Closed as completed by vanitasvitae** 2016-09-20 17:54 UTC
Labels: bug
