### ISSUE TITLE
Dandelion load the stream when I want to upload an image or switch from another app to Dandelion

### ISSUE THREAD

**Issue by Ravenbird** [gsantner/dandelion#190] opened 2018-03-29 09:50 UTC
#### General information
Dandelion 1.1.1 (30)
Android 7.1.1
BQ Auaris x5 plus
nerdpol.ch 0.7.9.9

#### Description
If I want to upload an image for a new post or switch to Dandelion from the start screen or another app, it reloads the stream for no apparent reason. I haven't found a way to stop it and it's extremely annoying if you just want to quickly shoot a picture and post it in or quickly check something in another app.

#### Further information
After the problem has been going on for a while now, I completely reset the system and reinstalled everything. Unfortunately, the problem persisted.

**Comment by gsantner** [comment] 2018-03-29 14:39
What was the latest version working for you? I still cannot reproduce your problem on any of 4 devices sadly, too there were not too much changes in the last 2-3 versions.

Mayto too: Did you have any OS(Android) updates or WebView updates since the working solution?

**Comment by gsantner** [comment] 2018-07-24 23:42
Closing as I cannot and not could ever reproduce the problem

**Closed as completed by gsantner** 2018-07-24 23:42 UTC
