### ISSUE TITLE
#Followed Hachtags" and "Aspects" are giving information in chinese (or japanese, dunno)!

### ISSUE THREAD

**Issue by Candidesk8** [gsantner/dandelion#81] opened 2016-10-14 11:15 UTC
#### General information
- **FairPhone FP1U :** 
- **Android 4.2.2 :** 
- **pod.framasphere.org :** 
- **0.6.0.0-pba27cf8f :**  
- **F-Droid :** 
- **0.1.6 (8) :** 

When trying to access to Aspects, instead of this:
<img width="30%" height="30%" src="https://raw.githubusercontent.com/Diaspora-for-Android/diaspora-android-extras/master/graphics/screens/0.1.6/09.png">
I got these :
<img width="30%" height="30%" src="https://framapic.org/JaBk7ew4jwAX/B64wCe2MmYmx">

When trying to access to Followed Hachtags, instead of this:
<img width="30%" height="30%" src="https://raw.githubusercontent.com/Diaspora-for-Android/diaspora-android-extras/master/graphics/screens/0.1.6/08.png">
I got these :
<img width="30%" height="30%" src="https://framapic.org/UzEiom0e30mu/cj2DeDDeYhCN">
#### Debug output

from DFA bug repport,, as asked on diaspora by _gsantner_ 
12:28:28: onCreate()
12:28:28: setupUI()
12:28:28: webViewPlaceholder had no child views
12:28:28: WebView was null. Create new one.
12:28:28: Add WebView to placeholder
12:28:29: setupUI: reload url
12:28:29: UI successfully set up
12:28:29: handleIntent()
12:28:29: Action: null Type: null
12:28:29: onResume()
12:28:29: Register BroadcastReceivers
12:28:29: onCreateOptionsMenu()
12:28:40: onOptionsItemSelected()
12:28:48: onNavigationItemsSelected()
12:28:48: onPause()
12:28:48: Unregister BroadcastReceivers
12:28:49: onSaveInstanceState()
12:28:49: Save WebView state
12:29:12: onResume()
12:29:12: Register BroadcastReceivers
12:29:15: onNavigationItemsSelected()
12:29:15: onPause()
12:29:15: Unregister BroadcastReceivers
12:29:16: onSaveInstanceState()
12:29:16: Save WebView state
12:29:24: Long click registered

```
```

**Comment by vanitasvitae** [comment] 2016-10-14 20:33
We'll try to reproduce this by creating an account on framasphere. Thank you very much for the bug report!

**Comment by vanitasvitae** [comment] 2016-10-14 20:54
I can reproduce this on a test account on an emulator with Android Jelly Bean (at least the aspects issue). The problem does not occur on later versions of Android though.

Since I couldn't reproduce the issue for the followed tags (which got a major redesign since the latest release) I guess the issues should be resolved in the next release (after the aspects got reworked as well).

Thank you again for that bug report!

Edit: The issue seems to be independent from the pod. I could also reproduce this on geraspora using a Jelly Bean emulator.

**Comment by gsantner** [comment] 2016-10-14 22:59
@vanitasvitae Could you pull (root required -> /data/data/com.github..) the shared preferences and attach them here? (No username/passwords or like that)

**Comment by gsantner** [comment] 2016-10-25 00:02
Should be resolved when **Hashtags** are ported over to a fragment.

**Comment by vanitasvitae** [comment] 2016-10-26 13:40
This should be fixed now

**Closed as completed by vanitasvitae** 2016-10-26 13:40 UTC
Labels: bug
