### ISSUE TITLE
post editor has erratic behaviour

### ISSUE THREAD

**Issue by stragu** [gsantner/dandelion#32] opened 2016-06-22 02:07 UTC
#### General information
- **Device:** Fair phone 1
- **Android Version:** 4.2.2
- **Pod:** joindiaspora.com
- **Diaspora pod version:** 0.5.9.99
- **App source:** F-Droid
- **App version:** 0.1.2

I have:
- [x] searched open and closed issues for duplicates
- [x] Diaspora for Android installed with an version >= 0.1.1
- [x] read https://github.com/Diaspora-for-Android/diaspora-android/blob/master/CONTRIBUTING.md
#### Steps to reproduce

1st behaviour:
1. Share something via "D\* New Message"
2. Paste some text
3. The text ends up in a different position, often in the middle of existing text.

2nd behaviour:
1. Share something via "D\* New Message" 
2. Start writing stuff
3. The text box often disappears. Writing is still registered and the user can edit blindly, and the text box can be restored by tapping the phone's "back" button.
#### Debug output

Will post debug output when find some time.

Does anyone else witness this behaviour?

**Comment by 4ndyD** [comment] 2016-06-22 16:13
Observed 2nd problem, of the text box disappearing until the android keyboard is minimised.

Text box also is too damn small, leaving over half the screen as wasted space, whether portrait or landscape, with a big gap still remaining after adding a photo.

**Comment by vanitasvitae** [comment] 2016-06-22 19:52
> Text box also is too damn small, leaving over half the screen as wasted space, whether portrait or landscape, with a big gap still remaining after adding a photo.

Due to the lack of a Diaspora API the app is just displaying the mobile view of your diaspora pod in a WebView (with extra functionality). So the size of the text box is defined by Diaspora's mobile site since it IS the actual displayed html.

We'll see what we can do though.

> 1. The text ends up in a different position, often in the middle of existing text.

That sounds strange. I'll see if we can reproduce and maybe fix this.

> 1. The text box often disappears. Writing is still registered and the user can edit blindly, and the text box can be restored by tapping the phone's "back" button.

Same here.

**Comment by gsantner** [comment] 2016-08-07 12:36
Any updates on this? I also cannot reproduce this (on <pod.geraspora.de>). Reopen if needed.

**Comment by 4ndyD** [comment] 2016-08-08 02:29
Just tested, it seems to have been fixed in the _New message_ page, but still get the keyboard covering posts in _Conversations_ if you load a long conversation, start replying, write a few lines, scroll up the page, scroll back down.
Again, fixed by minimising and restoring the keyboard, so not a major issue.

**Comment by stragu** [comment] 2016-08-08 02:48
I am still experiencing the first issue (pasted text ends up somewhere else) with version 0.1.4

**Comment by gsantner** [comment] 2016-08-08 06:26
I cannot reproduce any of these issues, on 4.2.2, 4.4, 6.0.  
I updated the sharing code, maybe this fixes one of your issues.  
We cannot fix something thats only happening on your device.

EDIT: The updates are **NOT** published as a release, it's on the GitHub master branch.

**Comment by vanitasvitae** [comment] 2016-08-21 15:06
I'll close this now because we cannot reproduce this and there is no feedback.

**Closed as completed by vanitasvitae** 2016-08-21 15:06 UTC
Labels: bug

**Comment by stragu** [comment] 2016-08-21 23:06
Fair enough, I figured out yesterday that it happened in a different app on my phone. It seems it's either the keyboard or the Android build.
Thank you!

**Comment by vanitasvitae** [comment] 2016-08-21 23:08
Thank you very much for your feedback :)
