### ISSUE TITLE
Aspects d'nt work

### ISSUE THREAD

**Issue by SergeyDjam** [gsantner/dandelion#108] opened 2016-11-04 13:50 UTC
Open aspect and view 
格浴㹬戼摯⁹瑳汹㵥洧牡楧⵮潴㩰㈠瀵㭸洠牡楧⵮敬瑦愺瑵㭯慭杲湩爭杩瑨愺瑵㭯映湯⵴楳敺›〴┰✻㰾灳湡猠祴敬✽慭杲湩氭晥㩴㌠瀰㭸✠㰾猯慰㹮爦煡潵※渦獢㭰愼栠敲㵦栧瑴獰⼺爯獵楳湡楤獡潰慲漮杲愯灳捥獴愿楟獤嵛㔽㤱✹猠祴敬✽潣潬㩲⌠〰〰〰※整瑸搭捥牯瑡潩㩮渠湯㭥㸧ꇐ뗐볐賑近⼼㹡格⁲瑳汹㵥栧楥桧㩴瀵㭸‧㸯猼慰⁮瑳汹㵥洧牡楧⵮敬瑦›〳硰※㸧⼼灳湡☾慲畱㭯☠扮灳㰻⁡牨晥✽瑨灴㩳⼯畲獳慩摮慩灳牯⹡牯⽧獡数瑣㽳彡摩孳㵝㈵〰‧瑳汹㵥挧汯牯›〣〰〰㬰琠硥⵴敤潣慲楴湯›潮敮✻퀾톔톀킃톷톌㲏愯㰾牨猠祴敬✽敨杩瑨㔺硰✻⼠㰾灳湡猠祴敬✽慭杲湩氭晥㩴㌠瀰㭸✠㰾猯慰㹮爦煡潵※渦獢㭰愼栠敲㵦栧瑴獰⼺爯獵楳湡楤獡潰慲漮杲愯灳捥獴愿楟獤嵛㔽〲✱猠祴敬✽潣潬㩲⌠〰〰〰※整瑸搭捥牯瑡潩㩮渠湯㭥㸧ꃐ냐뇐뻐苑냐⼼㹡格⁲瑳汹㵥栧楥桧㩴瀵㭸‧㸯猼慰⁮瑳汹㵥洧牡楧⵮敬瑦›〳硰※㸧⼼灳湡☾慲畱㭯☠扮灳㰻⁡牨晥✽瑨灴㩳⼯畲獳慩摮慩灳牯⹡牯⽧獡数瑣㽳彡摩孳㵝㈵㈰‧瑳汹㵥挧汯牯›〣〰〰㬰琠硥⵴敤潣慲楴湯›潮敮✻퀾킗킽킰킺킾톼킋㲵愯㰾牨猠祴敬✽敨杩瑨㔺硰✻⼠㰾灳湡猠祴敬✽慭杲湩氭晥㩴㌠瀰㭸✠㰾猯慰㹮爦煡潵※渦獢㭰愼栠敲㵦栧瑴獰⼺爯獵楳湡楤獡潰慲漮杲愯灳捥獴愿楟獤嵛㔽〶✳猠祴敬✽潣潬㩲⌠〰〰〰※整瑸搭捥牯瑡潩㩮渠湯㭥㸧铐룐냐臑뿐뻐胑냐⼼㹡格⁲瑳汹㵥栧楥桧㩴瀵㭸‧㸯⼼潢祤㰾栯浴㹬

**Comment by vanitasvitae** [comment] 2016-11-04 13:51
This has already been reported and is fixed. The issue will be gone in the upcoming release :+1: 
https://pod.geraspora.de/posts/5437212

Duplicate of #81

**Closed as completed by vanitasvitae** 2016-11-04 13:51 UTC
